# Generated by Django 4.2.4 on 2023-08-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
